/**
 * TradingView REST API Specification for Brokers
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version:
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.android.volley.VolleyError;

import java.io.UnsupportedEncodingException;

public class ApiException extends Exception {
  private int code;
  private String message;
  private VolleyError volleyError;

  public ApiException() {
  }

  public ApiException(int code, String message) {
    this.code = code;
    this.message = message;
  }

  public ApiException(int code, VolleyError volleyError) {
    this(code, volleyError.getMessage());
    this.volleyError = volleyError;
  }

  /**
   * Get the HTTP status code.
   *
   * @return HTTP status code
   */
  public int getCode() {
    return code;
  }

  /**
   * Set the HTTP status code.
   *
   * @param code HTTP status code.
   */
  public void setCode(int code) {
    this.code = code;
  }

  /**
   * Get the error message.
   *
   * @return Error message.
   */
  public String getMessage() {
    String networkResponse = getNetworkResponse();
    if (message == null) {
      return networkResponse;
    }
    return message + (networkResponse == null ? "" : "\n" + networkResponse);
  }

  /**
   * Set the error messages.
   *
   * @param message Error message.
   */
  public void setMessage(String message) {
    this.message = message;
  }

  public String getNetworkResponse() {
    try {
      if (volleyError == null) {
        return null;
      }
      return new String(volleyError.networkResponse.data, "UTF-8");
    } catch (UnsupportedEncodingException e) {
      e.printStackTrace();
      return null;
    }
  }
}
