/**
 * TradingView REST API Specification for Brokers
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version:
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;

@ApiModel(description = "")
public class AccountManagerTable {

  @SerializedName("id")
  private String id = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("columns")
  private List<AccountManagerColumn> columns = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  /**
   * Localized title of a table
   **/
  @ApiModelProperty(required = true, value = "Localized title of a table")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<AccountManagerColumn> getColumns() {
    return columns;
  }

  public void setColumns(List<AccountManagerColumn> columns) {
    this.columns = columns;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountManagerTable accountManagerTable = (AccountManagerTable) o;
    return (this.id == null ? accountManagerTable.id == null : this.id.equals(accountManagerTable.id)) &&
      (this.title == null ? accountManagerTable.title == null : this.title.equals(accountManagerTable.title)) &&
      (this.columns == null ? accountManagerTable.columns == null : this.columns.equals(accountManagerTable.columns));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
    result = 31 * result + (this.title == null ? 0 : this.title.hashCode());
    result = 31 * result + (this.columns == null ? 0 : this.columns.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountManagerTable {\n");

    sb.append("  id: ").append(id).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  columns: ").append(columns).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
