/**
 * TradingView REST API Specification for Brokers
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version:
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;

/**
 * Authorization Response
 **/
@ApiModel(description = "Authorization Response")
public class AuthorizationResponse {

  @SerializedName("access_token")
  private String accessToken = null;
  @SerializedName("expiration")
  private BigDecimal expiration = null;

  /**
   * Access token acts as a session ID that the application uses for making requests. This token should be protected as if it were user credentials
   **/
  @ApiModelProperty(required = true, value = "Access token acts as a session ID that the application uses for making requests. This token should be protected as if it were user credentials")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  /**
   * The time when the token is expired is represented as the number of seconds since the Unix epoch (00:00:00 UTC on 1 January 1970)
   **/
  @ApiModelProperty(required = true, value = "The time when the token is expired is represented as the number of seconds since the Unix epoch (00:00:00 UTC on 1 January 1970)")
  public BigDecimal getExpiration() {
    return expiration;
  }

  public void setExpiration(BigDecimal expiration) {
    this.expiration = expiration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationResponse authorizationResponse = (AuthorizationResponse) o;
    return (this.accessToken == null ? authorizationResponse.accessToken == null : this.accessToken.equals(authorizationResponse.accessToken)) &&
      (this.expiration == null ? authorizationResponse.expiration == null : this.expiration.equals(authorizationResponse.expiration));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.accessToken == null ? 0 : this.accessToken.hashCode());
    result = 31 * result + (this.expiration == null ? 0 : this.expiration.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationResponse {\n");

    sb.append("  accessToken: ").append(accessToken).append("\n");
    sb.append("  expiration: ").append(expiration).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
