/**
 * XchangeCrypt REST API Specification
 * TradingView REST API Specification for Brokers (ASP.NET Core 2.0)
 * <p>
 * OpenAPI spec version: v1
 * Contact:
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;

/**
 *
 **/
@ApiModel(description = "")
public class ConfigResponse {

  @SerializedName("accountManager")
  private List<AccountManagerTable> accountManager = null;
  @SerializedName("durations")
  private List<Duration> durations = null;
  @SerializedName("pullingInterval")
  private PullingInterval pullingInterval = null;

  /**
   * Localized account manager's tables configuration. Account Manager is a page in the bottom widget. This page can have multiple tables. Data of the tables is filled using `/state` response.
   **/
  @ApiModelProperty(value = "Localized account manager's tables configuration. Account Manager is a page in the bottom widget. This page can have multiple tables. Data of the tables is filled using `/state` response.")
  public List<AccountManagerTable> getAccountManager() {
    return accountManager;
  }

  public void setAccountManager(List<AccountManagerTable> accountManager) {
    this.accountManager = accountManager;
  }

  /**
   * Localized array of durations displayed in Order Ticket
   **/
  @ApiModelProperty(value = "Localized array of durations displayed in Order Ticket")
  public List<Duration> getDurations() {
    return durations;
  }

  public void setDurations(List<Duration> durations) {
    this.durations = durations;
  }

  /**
   * Gets or Sets PullingInterval
   **/
  @ApiModelProperty(value = "Gets or Sets PullingInterval")
  public PullingInterval getPullingInterval() {
    return pullingInterval;
  }

  public void setPullingInterval(PullingInterval pullingInterval) {
    this.pullingInterval = pullingInterval;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigResponse configResponse = (ConfigResponse) o;
    return (this.accountManager == null ? configResponse.accountManager == null : this.accountManager.equals(configResponse.accountManager)) &&
      (this.durations == null ? configResponse.durations == null : this.durations.equals(configResponse.durations)) &&
      (this.pullingInterval == null ? configResponse.pullingInterval == null : this.pullingInterval.equals(configResponse.pullingInterval));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.accountManager == null ? 0 : this.accountManager.hashCode());
    result = 31 * result + (this.durations == null ? 0 : this.durations.hashCode());
    result = 31 * result + (this.pullingInterval == null ? 0 : this.pullingInterval.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigResponse {\n");

    sb.append("  accountManager: ").append(accountManager).append("\n");
    sb.append("  durations: ").append(durations).append("\n");
    sb.append("  pullingInterval: ").append(pullingInterval).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
