/**
 * TradingView REST API Specification for Brokers
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version:
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;

/**
 * Depth of market for an instrument
 **/
@ApiModel(description = "Depth of market for an instrument")
public class Depth {

  @SerializedName("asks")
  private List<DepthItem> asks = null;
  @SerializedName("bids")
  private List<DepthItem> bids = null;

  /**
   * Array of Asks
   **/
  @ApiModelProperty(required = true, value = "Array of Asks")
  public List<DepthItem> getAsks() {
    return asks;
  }

  public void setAsks(List<DepthItem> asks) {
    this.asks = asks;
  }

  /**
   * Array of Bids
   **/
  @ApiModelProperty(required = true, value = "Array of Bids")
  public List<DepthItem> getBids() {
    return bids;
  }

  public void setBids(List<DepthItem> bids) {
    this.bids = bids;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Depth depth = (Depth) o;
    return (this.asks == null ? depth.asks == null : this.asks.equals(depth.asks)) &&
      (this.bids == null ? depth.bids == null : this.bids.equals(depth.bids));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.asks == null ? 0 : this.asks.hashCode());
    result = 31 * result + (this.bids == null ? 0 : this.bids.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Depth {\n");

    sb.append("  asks: ").append(asks).append("\n");
    sb.append("  bids: ").append(bids).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
