/**
 * TradingView REST API Specification for Brokers
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse20014 {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("p")
  private BigDecimal p = null;
  @SerializedName("s")
  private BigDecimal s = null;
  @SerializedName("t")
  private BigDecimal t = null;
  public enum FEnum {
     a,  b,  d,  t, 
  };
  @SerializedName("f")
  private FEnum f = null;
  @SerializedName("o")
  private BigDecimal o = null;
  @SerializedName("h")
  private BigDecimal h = null;
  @SerializedName("l")
  private BigDecimal l = null;
  @SerializedName("c")
  private BigDecimal c = null;
  @SerializedName("v")
  private BigDecimal v = null;

  /**
   * Symbol
   **/
  @ApiModelProperty(required = true, value = "Symbol")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Price
   **/
  @ApiModelProperty(value = "Price")
  public BigDecimal getP() {
    return p;
  }
  public void setP(BigDecimal p) {
    this.p = p;
  }

  /**
   * Size
   **/
  @ApiModelProperty(value = "Size")
  public BigDecimal getS() {
    return s;
  }
  public void setS(BigDecimal s) {
    this.s = s;
  }

  /**
   * Time
   **/
  @ApiModelProperty(required = true, value = "Time")
  public BigDecimal getT() {
    return t;
  }
  public void setT(BigDecimal t) {
    this.t = t;
  }

  /**
   * Type (a - ask, b - bid, t - trade, d - daily bar). Default value is `t` (trade).
   **/
  @ApiModelProperty(value = "Type (a - ask, b - bid, t - trade, d - daily bar). Default value is `t` (trade).")
  public FEnum getF() {
    return f;
  }
  public void setF(FEnum f) {
    this.f = f;
  }

  /**
   * Open
   **/
  @ApiModelProperty(value = "Open")
  public BigDecimal getO() {
    return o;
  }
  public void setO(BigDecimal o) {
    this.o = o;
  }

  /**
   * High
   **/
  @ApiModelProperty(value = "High")
  public BigDecimal getH() {
    return h;
  }
  public void setH(BigDecimal h) {
    this.h = h;
  }

  /**
   * Low
   **/
  @ApiModelProperty(value = "Low")
  public BigDecimal getL() {
    return l;
  }
  public void setL(BigDecimal l) {
    this.l = l;
  }

  /**
   * Close
   **/
  @ApiModelProperty(value = "Close")
  public BigDecimal getC() {
    return c;
  }
  public void setC(BigDecimal c) {
    this.c = c;
  }

  /**
   * Volume
   **/
  @ApiModelProperty(value = "Volume")
  public BigDecimal getV() {
    return v;
  }
  public void setV(BigDecimal v) {
    this.v = v;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20014 inlineResponse20014 = (InlineResponse20014) o;
    return (this.id == null ? inlineResponse20014.id == null : this.id.equals(inlineResponse20014.id)) &&
        (this.p == null ? inlineResponse20014.p == null : this.p.equals(inlineResponse20014.p)) &&
        (this.s == null ? inlineResponse20014.s == null : this.s.equals(inlineResponse20014.s)) &&
        (this.t == null ? inlineResponse20014.t == null : this.t.equals(inlineResponse20014.t)) &&
        (this.f == null ? inlineResponse20014.f == null : this.f.equals(inlineResponse20014.f)) &&
        (this.o == null ? inlineResponse20014.o == null : this.o.equals(inlineResponse20014.o)) &&
        (this.h == null ? inlineResponse20014.h == null : this.h.equals(inlineResponse20014.h)) &&
        (this.l == null ? inlineResponse20014.l == null : this.l.equals(inlineResponse20014.l)) &&
        (this.c == null ? inlineResponse20014.c == null : this.c.equals(inlineResponse20014.c)) &&
        (this.v == null ? inlineResponse20014.v == null : this.v.equals(inlineResponse20014.v));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.p == null ? 0: this.p.hashCode());
    result = 31 * result + (this.s == null ? 0: this.s.hashCode());
    result = 31 * result + (this.t == null ? 0: this.t.hashCode());
    result = 31 * result + (this.f == null ? 0: this.f.hashCode());
    result = 31 * result + (this.o == null ? 0: this.o.hashCode());
    result = 31 * result + (this.h == null ? 0: this.h.hashCode());
    result = 31 * result + (this.l == null ? 0: this.l.hashCode());
    result = 31 * result + (this.c == null ? 0: this.c.hashCode());
    result = 31 * result + (this.v == null ? 0: this.v.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20014 {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  p: ").append(p).append("\n");
    sb.append("  s: ").append(s).append("\n");
    sb.append("  t: ").append(t).append("\n");
    sb.append("  f: ").append(f).append("\n");
    sb.append("  o: ").append(o).append("\n");
    sb.append("  h: ").append(h).append("\n");
    sb.append("  l: ").append(l).append("\n");
    sb.append("  c: ").append(c).append("\n");
    sb.append("  v: ").append(v).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
