/**
 * TradingView REST API Specification for Brokers
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Expiration type and UNIX timestamp date/time
 **/
@ApiModel(description = "Expiration type and UNIX timestamp date/time")
public class OrderDuration {
  
  @SerializedName("type")
  private String type = null;
  @SerializedName("datetime")
  private BigDecimal datetime = null;

  /**
   * Duration ID. Internal ID that you set in ConfigResponse.
   **/
  @ApiModelProperty(required = true, value = "Duration ID. Internal ID that you set in ConfigResponse.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * Unit timestamp (UTC)
   **/
  @ApiModelProperty(value = "Unit timestamp (UTC)")
  public BigDecimal getDatetime() {
    return datetime;
  }
  public void setDatetime(BigDecimal datetime) {
    this.datetime = datetime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDuration orderDuration = (OrderDuration) o;
    return (this.type == null ? orderDuration.type == null : this.type.equals(orderDuration.type)) &&
        (this.datetime == null ? orderDuration.datetime == null : this.datetime.equals(orderDuration.datetime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.datetime == null ? 0: this.datetime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDuration {\n");
    
    sb.append("  type: ").append(type).append("\n");
    sb.append("  datetime: ").append(datetime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
