/**
 * XchangeCrypt REST API Specification
 * TradingView REST API Specification for Brokers (ASP.NET Core 2.0)
 * <p>
 * OpenAPI spec version: v1
 * Contact:
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ProfileDetails {

  @SerializedName("id")
  private String id = null;
  @SerializedName("login")
  private String login = null;
  @SerializedName("emailAddress")
  private String emailAddress = null;
  @SerializedName("realName")
  private String realName = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getRealName() {
    return realName;
  }

  public void setRealName(String realName) {
    this.realName = realName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileDetails profileDetails = (ProfileDetails) o;
    return (this.id == null ? profileDetails.id == null : this.id.equals(profileDetails.id)) &&
      (this.login == null ? profileDetails.login == null : this.login.equals(profileDetails.login)) &&
      (this.emailAddress == null ? profileDetails.emailAddress == null : this.emailAddress.equals(profileDetails.emailAddress)) &&
      (this.realName == null ? profileDetails.realName == null : this.realName.equals(profileDetails.realName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0 : this.id.hashCode());
    result = 31 * result + (this.login == null ? 0 : this.login.hashCode());
    result = 31 * result + (this.emailAddress == null ? 0 : this.emailAddress.hashCode());
    result = 31 * result + (this.realName == null ? 0 : this.realName.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileDetails {\n");

    sb.append("  id: ").append(id).append("\n");
    sb.append("  login: ").append(login).append("\n");
    sb.append("  emailAddress: ").append(emailAddress).append("\n");
    sb.append("  realName: ").append(realName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
