/**
 * XchangeCrypt REST API Specification
 * TradingView REST API Specification for Brokers (ASP.NET Core 2.0)
 * <p>
 * OpenAPI spec version: v1
 * Contact:
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Price response for an instrument
 **/
@ApiModel(description = "Price response for an instrument")
public class QuotesResponse {

  public enum SEnum {
    ok, error,
  }

  ;
  @SerializedName("s")
  private SEnum s = null;
  @SerializedName("n")
  private String n = null;
  @SerializedName("v")
  private SingleQuote v = null;

  /**
   * Gets or Sets S
   **/
  @ApiModelProperty(required = true, value = "Gets or Sets S")
  public SEnum getS() {
    return s;
  }

  public void setS(SEnum s) {
    this.s = s;
  }

  /**
   * Symbol name. Should be equal to the requested one
   **/
  @ApiModelProperty(required = true, value = "Symbol name. Should be equal to the requested one")
  public String getN() {
    return n;
  }

  public void setN(String n) {
    this.n = n;
  }

  /**
   * Gets or Sets V
   **/
  @ApiModelProperty(required = true, value = "Gets or Sets V")
  public SingleQuote getV() {
    return v;
  }

  public void setV(SingleQuote v) {
    this.v = v;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotesResponse quotesResponse = (QuotesResponse) o;
    return (this.s == null ? quotesResponse.s == null : this.s.equals(quotesResponse.s)) &&
      (this.n == null ? quotesResponse.n == null : this.n.equals(quotesResponse.n)) &&
      (this.v == null ? quotesResponse.v == null : this.v.equals(quotesResponse.v));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.s == null ? 0 : this.s.hashCode());
    result = 31 * result + (this.n == null ? 0 : this.n.hashCode());
    result = 31 * result + (this.v == null ? 0 : this.v.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotesResponse {\n");

    sb.append("  s: ").append(s).append("\n");
    sb.append("  n: ").append(n).append("\n");
    sb.append("  v: ").append(v).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
