/**
 * TradingView REST API Specification for Brokers
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Price data for an instrument
 **/
@ApiModel(description = "Price data for an instrument")
public class SingleQuote {
  
  @SerializedName("ch")
  private BigDecimal ch = null;
  @SerializedName("chp")
  private BigDecimal chp = null;
  @SerializedName("lp")
  private BigDecimal lp = null;
  @SerializedName("ask")
  private BigDecimal ask = null;
  @SerializedName("bid")
  private BigDecimal bid = null;
  @SerializedName("open_price")
  private BigDecimal openPrice = null;
  @SerializedName("high_price")
  private BigDecimal highPrice = null;
  @SerializedName("low_price")
  private BigDecimal lowPrice = null;
  @SerializedName("prev_close_price")
  private BigDecimal prevClosePrice = null;
  @SerializedName("volume")
  private BigDecimal volume = null;

  /**
   * Change (displayed in Watch and Detail)
   **/
  @ApiModelProperty(value = "Change (displayed in Watch and Detail)")
  public BigDecimal getCh() {
    return ch;
  }
  public void setCh(BigDecimal ch) {
    this.ch = ch;
  }

  /**
   * Change percent (displayed in Watch and Detail)
   **/
  @ApiModelProperty(value = "Change percent (displayed in Watch and Detail)")
  public BigDecimal getChp() {
    return chp;
  }
  public void setChp(BigDecimal chp) {
    this.chp = chp;
  }

  /**
   * Last price
   **/
  @ApiModelProperty(value = "Last price")
  public BigDecimal getLp() {
    return lp;
  }
  public void setLp(BigDecimal lp) {
    this.lp = lp;
  }

  /**
   * Ask price
   **/
  @ApiModelProperty(value = "Ask price")
  public BigDecimal getAsk() {
    return ask;
  }
  public void setAsk(BigDecimal ask) {
    this.ask = ask;
  }

  /**
   * Bid price
   **/
  @ApiModelProperty(value = "Bid price")
  public BigDecimal getBid() {
    return bid;
  }
  public void setBid(BigDecimal bid) {
    this.bid = bid;
  }

  /**
   * Open
   **/
  @ApiModelProperty(value = "Open")
  public BigDecimal getOpenPrice() {
    return openPrice;
  }
  public void setOpenPrice(BigDecimal openPrice) {
    this.openPrice = openPrice;
  }

  /**
   * High price
   **/
  @ApiModelProperty(value = "High price")
  public BigDecimal getHighPrice() {
    return highPrice;
  }
  public void setHighPrice(BigDecimal highPrice) {
    this.highPrice = highPrice;
  }

  /**
   * Low price
   **/
  @ApiModelProperty(value = "Low price")
  public BigDecimal getLowPrice() {
    return lowPrice;
  }
  public void setLowPrice(BigDecimal lowPrice) {
    this.lowPrice = lowPrice;
  }

  /**
   * Previous close price
   **/
  @ApiModelProperty(value = "Previous close price")
  public BigDecimal getPrevClosePrice() {
    return prevClosePrice;
  }
  public void setPrevClosePrice(BigDecimal prevClosePrice) {
    this.prevClosePrice = prevClosePrice;
  }

  /**
   * Volume
   **/
  @ApiModelProperty(value = "Volume")
  public BigDecimal getVolume() {
    return volume;
  }
  public void setVolume(BigDecimal volume) {
    this.volume = volume;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SingleQuote singleQuote = (SingleQuote) o;
    return (this.ch == null ? singleQuote.ch == null : this.ch.equals(singleQuote.ch)) &&
        (this.chp == null ? singleQuote.chp == null : this.chp.equals(singleQuote.chp)) &&
        (this.lp == null ? singleQuote.lp == null : this.lp.equals(singleQuote.lp)) &&
        (this.ask == null ? singleQuote.ask == null : this.ask.equals(singleQuote.ask)) &&
        (this.bid == null ? singleQuote.bid == null : this.bid.equals(singleQuote.bid)) &&
        (this.openPrice == null ? singleQuote.openPrice == null : this.openPrice.equals(singleQuote.openPrice)) &&
        (this.highPrice == null ? singleQuote.highPrice == null : this.highPrice.equals(singleQuote.highPrice)) &&
        (this.lowPrice == null ? singleQuote.lowPrice == null : this.lowPrice.equals(singleQuote.lowPrice)) &&
        (this.prevClosePrice == null ? singleQuote.prevClosePrice == null : this.prevClosePrice.equals(singleQuote.prevClosePrice)) &&
        (this.volume == null ? singleQuote.volume == null : this.volume.equals(singleQuote.volume));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ch == null ? 0: this.ch.hashCode());
    result = 31 * result + (this.chp == null ? 0: this.chp.hashCode());
    result = 31 * result + (this.lp == null ? 0: this.lp.hashCode());
    result = 31 * result + (this.ask == null ? 0: this.ask.hashCode());
    result = 31 * result + (this.bid == null ? 0: this.bid.hashCode());
    result = 31 * result + (this.openPrice == null ? 0: this.openPrice.hashCode());
    result = 31 * result + (this.highPrice == null ? 0: this.highPrice.hashCode());
    result = 31 * result + (this.lowPrice == null ? 0: this.lowPrice.hashCode());
    result = 31 * result + (this.prevClosePrice == null ? 0: this.prevClosePrice.hashCode());
    result = 31 * result + (this.volume == null ? 0: this.volume.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SingleQuote {\n");
    
    sb.append("  ch: ").append(ch).append("\n");
    sb.append("  chp: ").append(chp).append("\n");
    sb.append("  lp: ").append(lp).append("\n");
    sb.append("  ask: ").append(ask).append("\n");
    sb.append("  bid: ").append(bid).append("\n");
    sb.append("  openPrice: ").append(openPrice).append("\n");
    sb.append("  highPrice: ").append(highPrice).append("\n");
    sb.append("  lowPrice: ").append(lowPrice).append("\n");
    sb.append("  prevClosePrice: ").append(prevClosePrice).append("\n");
    sb.append("  volume: ").append(volume).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
